# Generated by Django 3.2.6 on 2021-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BhavcopyMasterPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkt_date', models.DateField()),
                ('mkt', models.BooleanField(default=False, verbose_name='Market')),
                ('series', models.CharField(max_length=10, verbose_name='Series')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('security', models.CharField(max_length=100, verbose_name='Name')),
                ('prev_close_price', models.FloatField(default=0.0)),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('net_trade_value', models.FloatField(default=0.0)),
                ('net_trade_qty', models.FloatField(default=0.0)),
                ('is_index', models.BooleanField(default=False, verbose_name='Is Index')),
                ('corp_index', models.CharField(max_length=5, verbose_name='Is Corp Index')),
                ('trades', models.FloatField(default=0.0)),
                ('fiftytwo_week_high', models.FloatField(default=0.0)),
                ('fiftytwo_week_low', models.FloatField(default=0.0)),
                ('is_nifty_fifty', models.BooleanField(default=False, verbose_name='Is Nifty 50')),
                ('is_nifty_next_fifty', models.BooleanField(default=False, verbose_name='Is Nifty Next 50')),
            ],
        ),
    ]
