# Generated by Django 3.2.6 on 2021-08-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopymasterpr',
            name='corp_index',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Is Corp Index'),
        ),
    ]
