# Generated by Django 3.2.6 on 2021-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmaster', '0004_bhavlastfiftydays_bhavlastfullyear_bhavlasthundreddays_bhavlasttendays'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianStockMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('stock_name', models.CharField(max_length=100, verbose_name='Name')),
                ('stock_first_data_date', models.DateField()),
                ('stock_last_data_date', models.DateField()),
                ('is_nifty_fifty', models.BooleanField(default=False, verbose_name='Is Nifty 50')),
                ('is_nifty_next_fifty', models.BooleanField(default=False, verbose_name='Is Nifty Next 50')),
                ('is_nifty_five_hundred', models.BooleanField(default=False, verbose_name='Is Nifty 500')),
            ],
        ),
    ]
