# Generated by Django 3.2.6 on 2021-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmaster', '0005_indianstockmasterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterstocks',
            name='stock_correction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
