# Generated by Django 3.2.6 on 2021-08-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockmaster', '0003_filterstocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAnalysisScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(auto_now=True)),
                ('return_on_capital_employed', models.CharField(choices=[(0.0, 'less than 5 percent'), (1.0, '5 to 10 percent'), (2.0, '10 to 15 percent'), (3.0, '15 to 20 percent'), (4.0, 'greater than 20 percent')], max_length=10)),
                ('earning_per_share', models.CharField(choices=[(0.0, 'No'), (1.0, 'Yes')], max_length=10)),
                ('free_cash_flow', models.CharField(choices=[(0.0, 'No'), (1.0, 'Yes')], max_length=10)),
                ('interest_coverage_ratio', models.CharField(choices=[(0.0, 'No'), (0.5, 'greater than 4'), (1.0, 'greater than 10')], max_length=10)),
                ('net_profit_margin', models.CharField(choices=[(-1.0, 'less than 5 percent'), (-0.5, '5 to 10 percent'), (1.0, '10 to 15 percent'), (2.0, '15 to 20 percent'), (3.0, 'greater than 20 percent')], max_length=10)),
                ('dividends', models.CharField(choices=[(0.0, 'No'), (1.0, 'Yes')], max_length=10)),
                ('government_regulations_risk', models.CharField(choices=[(0.0, 'No'), (-1.0, 'Yes')], max_length=10)),
                ('research_and_development_risk', models.CharField(choices=[(0.0, 'No'), (-1.0, 'Yes')], max_length=10)),
                ('key_person_risk', models.CharField(choices=[(0.0, 'No'), (-1.0, 'Yes')], max_length=10)),
                ('brand_loyalty_advantage', models.BooleanField(default=False)),
                ('cost_efficiency_advantage', models.BooleanField(default=False)),
                ('webbing_advantage', models.BooleanField(default=False)),
                ('stickiness_advantage', models.BooleanField(default=False)),
                ('number_of_moats', models.FloatField(default=0.0)),
                ('qualitative_score', models.FloatField(default=0.0)),
                ('filtered_security_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmaster.filterstocks', verbose_name='Filter Stock')),
            ],
        ),
    ]
