# Generated by Django 3.2.6 on 2021-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_auto_20210913_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrendSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('bullish_engulfing_signal', models.CharField(choices=[('Buy', 'BUY'), ('No Signal', 'No Signal')], max_length=15)),
                ('bullish_harami_signal', models.CharField(choices=[('Buy', 'BUY'), ('No Signal', 'No Signal')], max_length=15)),
                ('piercing_pattern_signal', models.CharField(choices=[('Buy', 'BUY'), ('No Signal', 'No Signal')], max_length=15)),
                ('morning_star_signal', models.CharField(choices=[('Buy', 'BUY'), ('No Signal', 'No Signal')], max_length=15)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
