# Generated by Django 3.2.6 on 2021-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0004_qualityanalysisscoring_stock_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityanalysisscoring',
            name='stock_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
