# Generated by Django 3.2.6 on 2024-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0005_qualityanalysisscoring_stock_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrendsignals',
            name='headnshoulder',
            field=models.CharField(blank=True, choices=[('Buy', 'BUY'), ('No Signal', 'No Signal')], max_length=15),
        ),
    ]
