# Generated by Django 3.2.6 on 2021-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRFolderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_date', models.DateField()),
                ('folder_link', models.URLField(max_length=500)),
                ('folder_status', models.CharField(choices=[('Generated', 'Generated'), ('Downloaded', 'Downloaded'), ('Not Available', 'Not Available')], default='Folder Status', max_length=200)),
            ],
        ),
    ]
